name: Build Executables
on: [push]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile Examen1.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Executable
          path: dist/Examen1.exe