name: Build Secure Executables

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller ttkbootstrap

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --uac-admin \
                   --hidden-import='ttkbootstrap' \
                   --collect-data='ttkbootstrap' \
                   Examen1.py
        
        if [ "$RUNNER_OS" == "Windows" ]; then
          mv dist/Examen1.exe dist/Examen1_${{ github.run_number }}.exe
          # Añadir información de versión
          exeinfo dist/Examen1_${{ github.run_number }}.exe /f VERSION
        else
          mv dist/Examen1 dist/Examen1_Mac_${{ github.run_number }}
          chmod +x dist/Examen1_Mac_${{ github.run_number }}
        fi

    - name: Add reputation (Windows)
      if: runner.os == 'Windows'
      run: |
        # Descarga Microsoft Defender tools
        curl -LO https://aka.ms/mp7zax
        Expand-Archive .\mp7zax -DestinationPath .\mp
        .\mp\mpcmdrun.exe -ScanFile -File dist/Examen1_${{ github.run_number }}.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Executable_${{ runner.os }}_${{ github.run_number }}
        path: dist/