name: Build Examen1 Executables

on:
  workflow_dispatch:  # Permite ejecución manual
  push:
    branches: [main]

on:
  push:
    tags: ['v*']

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # pip install -r requirements.txt
        
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed Examen1.py
        # Si tienes un icono para Windows:
        # pyinstaller --onefile --windowed --icon=app.ico Examen1.py
        mv dist/Examen1.exe dist/Examen1_Windows.exe
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: Examen1_Windows
        path: dist/Examen1_Windows.exe

  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # pip install -r requirements.txt
        
    - name: Build Mac application
      run: |
        pyinstaller --onefile --windowed Examen1.py
        chmod +x dist/Examen1
        mv dist/Examen1 dist/Examen1_Mac
        
        # Opcional: Crear bundle .app
        mkdir -p "dist/Examen1.app/Contents/MacOS"
        mkdir -p "dist/Examen1.app/Contents/Resources"
        cp dist/Examen1_Mac "dist/Examen1.app/Contents/MacOS/Examen1"
        # Si tienes un icono para Mac:
        # cp app.icns "dist/Examen1.app/Contents/Resources/"
        
        cat > "dist/Examen1.app/Contents/Info.plist" <<EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>Examen1</string>
            <key>CFBundleIdentifier</key>
            <string>com.yourdomain.Examen1</string>
            <key>CFBundleName</key>
            <string>Examen1</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
        </dict>
        </plist>
        EOL
    
    - name: Upload Mac artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Examen1_Mac
        path: |
          dist/Examen1_Mac
          dist/Examen1.app
